= Liang Yu Hao - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Contags
Contags is a desktop address book application used for business executives to efficiently connect with their contacts through effective management of contact details and ease of use in contacting them through integrated mail and SMS features. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com/CS2103AUG2017-T16-B4/main/blob/master/collated/main/mzxc152.md[Functional code]] [https://github.com/CS2103AUG2017-T16-B4/main/blob/master/collated/test/mzxc152.md[Test code]]

=== Enhancement Added: Sort

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification
The sort feature implemented in Contags allows you to easily look through the list of Contacts that you have saved in Contags
without looking through the whole list one contact at a time just to find that one particular contact. +
This reduces the time and effort required to find your contacts, making it more user-friendly.

Currently, the sort feature works by sorting your list of contacts either by Name, Phone, Email, Address or Tag, in alphabetical order.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sortusecase]

include::../DeveloperGuide.adoc[tag=sort]

#End of Extract#

---

=== Enhancement added: Tag colors

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=tagcolor]

#End of Extract#

---

==== Justification
The inclusion of tag colors for each unique tag allows users to differentiate easily between different tags at a glance, without
having to look through the list or using the `find` or `sort` command to search tags. Colors also allow for better memory retention of specific groups
to help increase the productivity of users when organising and looking thorugh their contacts.

Currently, the tag colors are a predefined string of colors, which can be seen in the code snippet in the implementation section.

==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=tagcolor]

#End of Extract#

---
=== Enhancement Proposed: Add command `change`

A `change` feature which allows users to change the color of each unique tag in their contacts list to the color of the choice.

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=change]

#End of Extract#

=== Other contributions

* Updated the GUI with a UI dropdown box for sorting, and also a find field for easy finding without having to type `find KEYWORD` in the main command line bar. +
(Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/39[#39])
* Updated Appendix C: Non Functional Requirements. +
(Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/34[#34])
* Updated Appendix E: Product Survey - included Microsoft People App. +
(Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/73[#73])
