= Liang Yu Hao - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Contags
Contags is a desktop address book application used for business executives to efficiently connect with their contacts through effective management of contact details and ease of use in contacting them through integrated mail and SMS features. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 6 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Sort

==== External behavior

---
#Start of Extract [from: User Guide]#

#End of Extract#

---

==== Justification
The sort feature implemented in Contags allows business executives to easily look through the list of Contacts that they have saved in Contags without looking through the whole list one contact at a time just to find that one particular contact.+

{Justify the need for, and the current design (i.e. external behavior) of, the feature}

==== Implementation

---
#Start of Extract [from: Developer Guide]#


#End of Extract#

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Updated the GUI with a UI dropdown box for sorting, and also a find field for easy finding without having to type `find KEYWORD` in the main command line bar.(Pull requests https://github.com[#33], https://github.com[#34])
