= Tiyyagura Hyma - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Contags
Contags is a desktop address book application that is targeted at business professionals. Contags, developed by Team CS2103-T16-B4, is an enhancement and further development of [https://github.com/se-edu/addressbook-level4[AddressBook - Level 4]], created by team SE-EDU as part of the module 2103, offered by the School of Computing in National University of Singapore. The user interacts with Contags primarily using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Mail Command

==== External behavior

include::../UserGuide.adoc[tag=mailContact]

---

==== Justification
As Contags was developed with working professionals in mind, having a mail command was of very high priority. Mail is the most widely used application by business professionals and according to a study done by The Radicarti Group, the average business professional sends 35 emails a day. Having a mail command integrated into an address book application would really make it more convenient for users who can find contacts easily and email them.

==== Implementation

include::../DeveloperGuide.adoc[tag=mailContact]
include::../DeveloperGuide.adoc[tag=mailcommand]

---

=== Enhancement Added: Birthday Field

==== Justification

Business professionals would find it useful to keep track of their contacts' birthdays so that they can maintain business relationships on top of friendships and family relationships. In today's world where connections are so necessary and powerful, maintaining business relationships have never been more important. One of the most important ways to maintain any relationship is to wish the person a happy birthday. Integrating a birthday field as part of a contact's particulars would help users to have a record of their contacts' birthdays.

==== Implementation

---

include::../DeveloperGuide.adoc[tag=birthdayfield]

---

=== Enhancement Added: ListBirthday Command

==== External behavior

---

include::../UserGuide.adoc[tag=listBirthday]

---

==== Justification

As mentioned, the birthday field is an important aspect of a contact's particulars due to the strong business relationships it can forge. To make the birthday field more useful, a listbirthday command is also implemented. This command lists the contacts whose birthday fall on that particular day. Users can then easily send them a mail or SMS by typing in the respective commands.

==== Implementation

---

include::../DeveloperGuide.adoc[tag=listBirthday]

---

=== Developer Guide Glossary

---

include::../DeveloperGuide.adoc[tag=glossary]

---

=== Enhancement Proposed: Add command `schedule`

A schedule feature would allow users to create events such as meetings or dinner with other contacts.

=== Other contributions

* Added alias for commands (Pull request https://github.com[#22])
* Added a backup to store contents of addressbook (Pull request https://github.com[#23])
* Added birthday field (Pull request https://github.com[#37])
* Updated UI to include a separate browser panel displaying the address of a contact when contact is selected (Pull request https://github.com[#107]])
* Enhanced find command to find by tags (Pull request https://github.com[#111])

== Project:

{Optionally (not graded), you may include other projects in your portfolio.}
