= Tiyyagura Hyma - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: Contags
Contags is a desktop address book application that is targeted at business professionals. Contags, developed by Team CS2103-T16-B4, is an enhancement and further development of [https://github.com/se-edu/addressbook-level4[AddressBook - Level 4]], created by team SE-EDU as part of the module 2103, offered by the School of Computing in National University of Singapore. The user interacts with Contags primarily using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

*Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] {give links to collated code files}

=== Enhancement Added: Mail Command

==== External behavior

include::../UserGuide.adoc[tag=mailContact]

===== Use Case

include::../DeveloperGuide.adoc[tag=mailContact]

---

==== Justification
As Contags was developed with working professionals in mind, having a mail command was of very high priority. Mail is the most widely used application by business professionals and according to a study done by The Radicarti Group, the average business professional sends 35 emails a day. Having a mail command integrated into an address book application would be more convenient for users who can find contacts easily and email them.

==== Implementation

include::../DeveloperGuide.adoc[tag=mailcommand]

---

=== Enhancement Added: Birthday Field

---

==== Justification

Business professionals would find it useful to keep track of their contacts' birthdays so that they can maintain business relationships on top of friendships and family relationships. In today's world where connections are so necessary and powerful, maintaining business relationships have never been more important. Integrating a birthday field as part of a contact's particulars would help users to have a record of their contacts' birthdays and would make it more convenient for users to wish the colleagues and friends.

---

==== Implementation

include::../DeveloperGuide.adoc[tag=birthdayfield]

---

=== Enhancement Added: ListBirthday Command

---

==== External behavior


include::../UserGuide.adoc[tag=listBirthday]

---

==== Justification

As mentioned, the birthday field is an important aspect of a contact's particulars due to the strong business relationships it can forge. To make the birthday field more useful, a listbirthday command is also implemented. This command lists the contacts whose birthday fall on that particular day. Users can then easily send them a mail or SMS by typing in the respective commands.

==== Implementation

include::../DeveloperGuide.adoc[tag=listBirthday]

---

=== Enhancement Added: BackUpAddressBook

---

==== Justification

==== Implementation

include::../DeveloperGuide.adoc[tag=backup]

=== Enhancement Added: Alias for Commands

==== Justification

We wanted users to be able to execute their desired commands with as little effort as possible. Therefore, we have added an alternative alias for commands to minimise the amount of typing they have to do.
See (Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/22[#22], Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/124[#124]).

---

=== Developer Guide Appendix: Glossary

include::../DeveloperGuide.adoc[tag=glossary]

---

=== Developer Guide Appendix: Product Survey

---

include::../DeveloperGuide.adoc[tag=productSurvey]

---

=== Enhancement Proposed: Add command `schedule`

A schedule feature would allow users to create events such as meetings or dinner with other contacts.

=== Other contributions

* Added a backup to store contents of addressbook (Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/23[#23])
* Added birthday field (Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/37[#37])
* Updated UI to add new logo and include a separate browser panel displaying the address of a contact when contact is selected (Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/107[#107]])
* Enhanced find command to find by tags (Pull request https://github.com/CS2103AUG2017-T16-B4/main/pull/111[#111])

== Project:

{Optionally (not graded), you may include other projects in your portfolio.}
